[tool.pydocstyle]
select = "D101,D102,D103,D105,D106"

[tool.mypy]
disable_error_code = "misc"
show_error_codes = true
files = "**/*.py"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
warn_unreachable = true
plugins = "pydantic.mypy"

[[tool.mypy.overrides]]
module = 'tests.*'
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_decorators = false
